mappings:
  RemoteFileForm: SilverStripe\AssetAdmin\Forms\RemoteFileFormFactory
  SiteConfig: SilverStripe\SiteConfig\SiteConfig
  SiteConfigLeftAndMain: SilverStripe\SiteConfig\SiteConfigLeftAndMain
